- frontend/src/components/layouts/Footer/index.js
> Removed cloudinary logo

- frontend/src/components/navbars/GlobalNavBar/index.js
> Added link to main page

- frontend/src/pages/_organise/default/EventsList.js
Bugfix for event banners and ability to search created events in 'Create Event' menu
> Banner bugfix and event search

- frontend/src/components/generic/Markdown/index.js
> Fix: mobile img bug on event description

- backend/package-lock.json
- backend/package.json
Updating mongoose to 5.10. higher version breaks the build.
fixes: #456
> Downgrading mongoose to older version

- frontend/src/App.js
- frontend/src/redux/user/actions.js
Downgrading mongoose back to version 5.9.
Having a higher version breaks the build.
Have to investigate why it breaks the build.
> Downgrading mongoose to older version.

- frontend/src/components/layouts/SidebarLayout/index.js
> fix for #460

- DOCUMENTATION.md
Added initial docs based on the great work by the CraftHub team. A lot to do still, but it's a start. Feel free to contribute :)
> Documentation for event organizers

- backend/common/services/webhook.js
- backend/modules/project/model.js
- backend/modules/registration/model.js
- frontend/src/pages/_organise/slug/edit/other/WebhooksForm.js
Refactors the existing webhook implementation and adds an additional webhook for `Registrations`. ]]
When saved, it will show up among existing webhooks:
This allows extensions such as this one: https://github.com/biharygergo/junctionapp-mailchimp-extension
> Webhooks for Registrations

- backend/modules/registration/helpers.js
- frontend/src/pages/_events/slug/register/RegistrationSection/index.js
- shared/constants/registration-fields.js
https://github.com/hackjunction/JunctionApp/issues/471
> 471_check_age_relative_to_event_start

- frontend/src/pages/_organise/slug/edit/default/index.js
> Bugfix for organizations field is infilled with null when selected empty

- backend/modules/user-profile/routes.js
- frontend/src/components/projects/ProjectDetail/ProjectTeam.js
- frontend/src/components/projects/ProjectDetail/ShareProject.js
- frontend/src/components/projects/ProjectDetail/index.js
- frontend/src/pages/_projects/slug/view/projectId/ScoreForm.js
- frontend/src/pages/_projects/slug/view/projectId/index.js
- frontend/src/services/userProfiles.js
Makes it easier for partner, who have recruitment access, to view profiles who are interested about recruitment.
A link to recruitment profile is shown next to persons in project detail page.
Some little css updates
> Recruitment link next to persons in project detail page

- frontend/src/components/projects/ProjectsGrid/index.js
- frontend/src/pages/_projects/slug/challenge/token/index.js
- frontend/src/pages/_projects/slug/view/projectId/ScoreForm.js
- frontend/src/pages/_projects/slug/view/projectId/index.js
Think about doing the filter more efficiently later
> partner project view status filter & hotfix to projectscores

- backend/modules/event/controller.js
- backend/modules/event/graphql.js
- backend/modules/event/model.js
- backend/modules/event/routes.js
- frontend/src/components/events/EventPageScript/index.js
- frontend/src/components/events/EventPageScriptIFrame/index.js
- frontend/src/pages/_dashboard/slug/default/index.js
- frontend/src/pages/_events/index.js
- frontend/src/pages/_events/slug/context.js
- frontend/src/pages/_events/slug/default/index.js
- frontend/src/pages/_events/slug/register/index.js
- frontend/src/pages/_events/slug/tracking/index.js
- frontend/src/pages/_index/index.js
- frontend/src/pages/_organise/slug/edit/other/PageScriptsForm.js
- frontend/src/pages/_organise/slug/edit/other/index.js
- frontend/src/pages/_pricing/index.js
- frontend/src/services/events.js
- frontend/src/utils/events.js
- shared/constants/event-page-scripts.js
- shared/index.js
- shared/schemas/EventPageScript.js
- shared/schemas/index.js
This is a copy of https://github.com/hackjunction/JunctionApp/pull/537 but this time it's rebased to master and going straight to master.
> Custom scripts clean

- frontend/src/constants/config.js
- frontend/src/pages/_organise/slug/stats/index.js
integrated metabase into organisers' stats view
> stats feature

- frontend/src/components/tables/ProjectsTable/index.js
Copy of https://github.com/hackjunction/JunctionApp/pull/557
Tiny change that adds two new columns to the Projects table on the Admin page.
> New columns on projects table

- frontend/src/pages/_events/slug/default/index.js
Copy of https://github.com/hackjunction/JunctionApp/pull/559
> fix: Link colors are sometimes incorrect

- backend/modules/event/graphql.js
- backend/modules/event/model.js
- frontend/public/locales/en/translation.json
- frontend/src/components/events/EventHeroImage/index.js
- frontend/src/components/inputs/EventNewsLetterButton/index.js
- frontend/src/pages/_events/slug/context.js
- frontend/src/pages/_events/slug/register/index.js
- frontend/src/pages/_organise/slug/edit/default/index.js
- frontend/src/pages/_organise/slug/stats/index.js
Copy of https://github.com/hackjunction/JunctionApp/pull/560
> feat: Add option to set event newsletter form

- frontend/src/pages/_events/slug/context.js
- frontend/src/pages/_events/slug/default/EventButtons/index.js
- frontend/src/pages/_events/slug/default/index.js
- frontend/src/pages/_organise/slug/edit/default/const.js
- frontend/src/pages/_organise/slug/edit/default/index.js
- shared/schemas/EventTheme.js
Reverts hackjunction/JunctionApp#565
> Revert "feat: Add option to hide Banner on event landing page"

- frontend/src/pages/_events/slug/voteWithToken/index.js
- frontend/src/pages/_organise/slug/projects/votingTokens/index.js
Reverts hackjunction/JunctionApp#570
> Revert "fix: Voting token queryParams conflict"
